language: cpp
sudo: required
services: docker

git:
  depth: 3
  submodules: false

before_install:
  - docker build -t gg-travis -f .travis.Dockerfile .

script:
  - docker run --cap-add=SYS_PTRACE -ti gg-travis:latest /home/user/gg/.travis-check.sh
