language: cpp
sudo: required
services: docker

git:
  depth: 3
  submodules: false

before_install:
  - docker build -t gg-travis -f .travis.Dockerfile .

script:
  - docker run -e COMMIT=${TRAVIS_COMMIT} --cap-add=SYS_PTRACE -ti gg-travis:latest ./check.sh

notifications:
  slack: keithw:RFEz0IvxWUHbHFan10UNb3Qo
